#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d D6 D7 D8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

polybar &
picom &
feh --bg-scale /usr/share/backgrounds/linuxmint-wilma/mpiwnicki_sunset.jpg &
bluetoothctl power off &
